#!/bin/bash

room=${1}

function exit()
{
	loop=0
	mosquitto_pub -h 192.168.1.1 -t cmnd/tasmota-${room}/POWER -m 1
	mosquitto_pub -h 192.168.1.1 -t cmnd/tasmota-${room}/CT -m 200
	mosquitto_pub -h 192.168.1.1 -t cmnd/tasmota-${room}/Dimmer -m 50
}

trap 'exit' 1 2 3 6

loop=1

while [ "${loop}" != "0" ]
do
	[[ "$i" = "100" ]] && add=-5
	[[ "$i" = "0" ]] && add=5

	i=$((i + add))
	mosquitto_pub -h 192.168.1.1 -t cmnd/tasmota-${room}/Dimmer -m ${i}
	sleep 0.1
done
